name: bdp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib
  - pandas
  - gym
  - pip
  - pip:
    - stable-baselines3[extra]
    - torch
    - opencv-python
    - ale-py
    - pyglet
    - box2d-py
    - pybullet